name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Environment
      run: sudo apt-get update && curl -Lo kitware-archive.sh https://apt.kitware.com/kitware-archive.sh && sudo bash ./kitware-archive.sh
    - name: Install Dependencies
      run: sudo apt-get install ninja-build cmake
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt-hotspot
        java-version: 11
        cache: gradle
    - name: Build
      run: bash ./gradlew --info assembleNormalRecordDebug assembleNormalRecordRelease bundleNormalNoRecordRelease bundleEmbedRecordRelease bundleEmbedNoRecordRelease
    - name: Artifact Failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: inspect_cxx
        path: app/build/intermediates/cxx/Debug
    - name: Artifact (Normal debug APK)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-debug.apk
        path: app/build/outputs/apk/normalRecord/debug/app-normal-record-debug.apk
    - name: Artifact (Normal unsigned APK)
      uses: actions/upload-artifact@v2
      with:
        name: love-android.apk
        path: app/build/outputs/apk/normalRecord/release/app-normal-record-release-unsigned.apk
    - name: Artifact (Normal AAB w/o recording)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-ps.aab
        path: app/build/outputs/bundle/normalNoRecordRelease/app-normal-noRecord-release.aab
    - name: Artifact (Embed AAB)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-embed-record.aab
        path: app/build/outputs/bundle/embedRecordRelease/app-embed-record-release.aab
    - name: Artifact (Embed AAB w/o recording)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-embed.aab
        path: app/build/outputs/bundle/embedNoRecordRelease/app-embed-noRecord-release.aab
